services:
  webapp:
    image: webapp
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_URL=mysql://user:password@database:3306/webapp_db
    depends_on:
      - database
  
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

tests:
    build: .
    depends_on:
      - webapp
      - db
    environment:
      - API_URL=https://webapp:3000
    command: yarn test

volumes:
  mysql_data: