name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installing nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing the dependencies using yarn
        run: yarn install

      - name: Running lint
        env:
          ESLINT_USE_FLAT_CONFIG: false
        run: yarn lint
