name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installing nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing the dependencies using yarn
        run: yarn install

      - name: Running lint
        env:
          ESLINT_USE_FLAT_CONFIG: false
        run: yarn lint

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Building the docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp
          push: true
